export const actionTypes = {
    LOGIN_CALL_REQUEST: "LOGIN_CALL_REQUEST",
    LOGIN_CALL_SUCCESS: "LOGIN_CALL_SUCCESS",
    LOGIN_CALL_FAILURE: "LOGIN_CALL_FAILURE",

    FETCH_OTP_REQUEST: "FETCH_OTP_REQUEST",
    FETCH_OTP_SUCCESS: "FETCH_OTP_SUCCESS",
    FETCH_OTP_ERROR: "FETCH_OTP_ERROR",

    GET_USER_DETAILS: "GET_USER_DETAILS",

    FETCH_COURSES_REQUEST: "FETCH_COURSES_REQUEST",
    FETCH_COURSES_SUCCESS: "FETCH_COURSES_SUCCESS",
    FETCH_COURSES_FAILURE: "FETCH_COURSES_FAILURE",

    GET_FILTERED_COURSES: "GET_FILTERED_COURSES",
    GET_SELECTED_COURSES: "GET_SELECTED_COURSES",

    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    GET_FILTERED_USERS: "GET_FILTERED_USERS",
    GET_SELECTED_USERS: "GET_SELECTED_USERS",

    GET_SLIDER_DURATION: "GET_SLIDER_DURATION",
    GET_LEARNING_PATH_NAME: "GET_LEARNING_PATH_NAME",
    GET_LEARNING_PATH_DES: "GET_LEARNING_PATH_DES",
    GET_LEARNING_PATH_LEVEL: "GET_LEARNING_PATH_LEVEL",
    SHOW_BUTTON_BASED_ON_RATE:"SHOW_BUTTON_BASED_ON_RATE",      

    PATH_MODEL_OPEN: "PATH_MODEL_OPEN",
    DISCARD_MODEL_OPEN: "DISCARD_MODEL_OPEN",

    CREATE_LEARNING_PATH_CALL_REQUEST: "CREATE_LEARNING_PATH_CALL_REQUEST",
    CREATE_LEARNING_PATH_CALL_SUCCESS: "CREATE_LEARNING_PATH_CALL_SUCCESS",
    CREATE_LEARNING_PATH_CALL_FAILURE: "CREATE_LEARNING_PATH_CALL_FAILURE",

    LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
    LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",

    GET_FIRST_NEXT_CLICKED: "GET_FIRST_NEXT_CLICKED",

    GET_ACTIVE_PATH_STEP: "GET_ACTIVE_PATH_STEP",

    GET_ASSIGNED_LEARNING_PATH_REQUEST: "GET_ASSIGNED_LEARNING_PATH_REQUEST",
    GET_ASSIGNED_LEARNING_PATH_SUCCESS: "GET_ASSIGNED_LEARNING_PATH_SUCCESS",
    GET_ASSIGNED_LEARNING_PATH_FAILURE: "GET_ASSIGNED_LEARNING_PATH_FAILURE",

    GET_LEARNING_PATH_COURSES_REQUEST: "GET_LEARNING_PATH_COURSES_REQUEST",
    GET_LEARNING_PATH_COURSES_SUCCESS: "GET_LEARNING_PATH_COURSES_SUCCESS",
    GET_LEARNING_PATH_COURSES_FAILURE: "GET_LEARNING_PATH_COURSES_FAILURE",
    
    GET_LEARNING_PATH_REQUEST: "GET_LEARNING_PATH_REQUEST",
    GET_LEARNING_PATH_SUCCESS: "GET_LEARNING_PATH_SUCCESS",
    GET_LEARNING_PATH_FAILURE: "GET_LEARNING_PATH_FAILURE",

    GET_MY_LEARNING_PATH_REQUEST: "GET_MY_LEARNING_PATH_REQUEST",
    GET_MY_LEARNING_PATH_SUCCESS: "GET_MY_LEARNING_PATH_SUCCESS",
    GET_MY_LEARNING_PATH_FAILURE: "GET_MY_LEARNING_PATH_FAILURE",
    CHANGE_COURSE_RATE:"CHANGE_COURSE_RATE",
    SAVE_COURSE_RATE:"SAVE_COURSE_RATE",
    SAVE_COURSE_RATE_SUCCESS:"SAVE_COURSE_RATE_SUCCESS",
    SAVE_COURSE_RATE_FAILURE:"SAVE_COURSE_RATE_FAILURE",
    
    VIEW_ATTACHMENT:"VIEW_ATTACHMENT",
    VIEW_ATTACHMENT_SUCCESS:"VIEW_ATTACHMENT_SUCCESS",
    VIEW_ATTACHMENT_FAILURE:"VIEW_ATTACHMENT_FAILURE",
    ADD_CERTIFICATE:"ADD_CERTIFICATE",
    UPLOAD_CERTIFICATE:"UPLOAD_CERTIFICATE",
    UPLOAD_CERTIFICATE_SUCCESS:"UPLOAD_CERTIFICATE_SUCCESS",
    UPLOAD_CERTIFICATE_FAILURE:"UPLOAD_CERTIFICATE_FAILURE",

    DELETE_ALL_PATH: "DELETE_ALL_PATH",
    DELETE_ALL_PATH_SUCCESS: "DELETE_ALL_PATH_SUCCESS",
    DELETE_ALL_PATH_FAILURE: "DELETE_ALL_PATH_FAILURE",
    
    DELETE_PATH: "DELETE_PATH",
    DELETE_PATH_SUCCESS: "DELETE_PATH_SUCCESS",
    DELETE_PATH_FAILURE: "DELETE_PATH_FAILURE",

    UPLOADFILE_MODEL_OPEN:'UPLOADFILE_MODEL_OPEN',

    CREATE_ASSIGNED_LEARNING_PATH_REQUEST: "CREATE_ASSIGNED_LEARNING_PATH_REQUEST",
    CREATE_ASSIGNED_LEARNING_PATH_SUCCESS: "CREATE_ASSIGNED_LEARNING_PATH_SUCCESS",
    CREATE_ASSIGNED_LEARNING_PATH_FAILURE: "CREATE_ASSIGNED_LEARNING_PATH_FAILURE",

    CREATE_ASSIGNED_LEARNING_PATH_CALL_REQUEST: "CREATE_ASSIGNED_LEARNING_PATH_CALL_REQUEST",
    CREATE_ASSIGNED_LEARNING_PATH_CALL_SUCCESS: "CREATE_ASSIGNED_LEARNING_PATH_CALL_SUCCESS",
    CREATE_ASSIGNED_LEARNING_PATH_CALL_FAILURE: "CREATE_ASSIGNED_LEARNING_PATH_CALL_FAILURE",
    REJECT: 'REJECT',
    APPROVE: 'APPROVE',

    GET_PENDING_APPROVAL:'GET_PENDING_APPROVAL',
    FETCH_PENDING_FOR_APPROVAL_SUCCESS:'FETCH_PENDING_FOR_APPROVAL_SUCCESS',
    FETCH_PENDING_FOR_APPROVAL_FAILURE:'FETCH_PENDING_FOR_APPROVAL_FAILURE',

    FETCH_APPROVAL_SUCCESS:'FETCH_APPROVAL_SUCCESS',
    FETCH_APPROVAL_FAILURE:'FETCH_APPROVAL_FAILURE',
    GET_APPROVAL_REJECTION:'GET_APPROVAL_REJECTION',

    SELECTED_LEARNING_PATH:'SELECTED_LEARNING_PATH',

    CLEAR_CREATE_LP_FORM:'CLEAR_CREATE_LP_FORM',
    CHANGE_DOC_UPLOAD_STATUS_FOR_COURSE:'CHANGE_DOC_UPLOAD_STATUS_FOR_COURSE',

    MANAGER_DASHBOARD_STATS_REQUEST:'MANAGER_DASHBOARD_STATS_REQUEST',
    MANAGER_DASHBOARD_STATS_SUCCESS:'MANAGER_DASHBOARD_STATS_SUCCESS',
    MANAGER_DASHBOARD_STATS_FAILURE:'MANAGER_DASHBOARD_STATS_FAILURE',

    POPULAR_STUFF_REQUEST:'POPULAR_STUFF_REQUEST',
    POPULAR_STUFF_SUCCESS:'POPULAR_STUFF_SUCCESS',
    POPULAR_STUFF_FAILURE:'POPULAR_STUFF_FAILURE'
}
