export const actionTypes = {
    LOGIN_CALL_REQUEST: "LOGIN_CALL_REQUEST",
    LOGIN_CALL_SUCCESS: "LOGIN_CALL_SUCCESS",
    LOGIN_CALL_FAILURE: "LOGIN_CALL_FAILURE",

    FETCH_OTP_REQUEST: "FETCH_OTP_REQUEST",
    FETCH_OTP_SUCCESS: "FETCH_OTP_SUCCESS",
    FETCH_OTP_ERROR: "FETCH_OTP_ERROR",

    GET_USER_DETAILS: "GET_USER_DETAILS",

    FETCH_COURSES_REQUEST: "FETCH_COURSES_REQUEST",
    FETCH_COURSES_SUCCESS: "FETCH_COURSES_SUCCESS",
    FETCH_COURSES_FAILURE: "FETCH_COURSES_FAILURE",

    GET_FILTERED_COURSES: "GET_FILTERED_COURSES",
    GET_SELECTED_COURSES: "GET_SELECTED_COURSES",

    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    GET_FILTERED_USERS: "GET_FILTERED_USERS",
    GET_SELECTED_USERS: "GET_SELECTED_USERS",
}
