import { makeStyles } from "@material-ui/core/styles";
import { blue, red } from "@material-ui/core/colors";
export const useStyles = makeStyles((theme) => ({
  root: {
    width: "98%",
    height: "70px",
    margin: "0 0 30px",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "2px 4px 10px 0 rgba(0, 0, 0, 0.1)",
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "center",
    [theme.breakpoints.up('md')]: {
      //width: "1140px",
      height: "70px",
      margin: "0 0 30px",
      padding: "20px",
      borderRadius: "8px",
      boxShadow: "2px 4px 10px 0 rgba(0, 0, 0, 0.1)",
      backgroundColor: "#ffffff",
      display: "flex",
      alignItems: "center",
    },
    [theme.breakpoints.up('lg')]: {
      //width: "1040px",
      height: "80px",
      margin: "0 0 30px",
      padding: "20px",
      borderRadius: "8px",
      boxShadow: "2px 4px 10px 0 rgba(0, 0, 0, 0.1)",
      backgroundColor: "#ffffff",
      display: "flex",
      alignItems: "center",
    },
  },
  head: {
    display: "flex",
    margin: "145px 0 0 100px",
  },
  approve: {
    padding: "0 0 0 20px",
    width: "120px",
    height: "50px",
    margin: "5px 30px 5px 34px",
    padding: "15px 21px 11px 22px",
    borderRadius: "4px",
    backgroundImage: "linear-gradient(to bottom, #ffab39, #f07200)",
    display: "flex",
    justifyContent: "center",
    color: "white"
  },
  view: {
    padding: "0 0 0 20px",
    width: "141px",
    height: "16px",
    margin: "0px 30px 10px 34px",
    padding: "15px 21px 11px 22px",
    borderRadius: "4px",
    display: "flex",
    justifyContent: "center",
    //fontFamily: "ProximaNova",
    fontSize: "12px",
    fontweight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1.23",
    letterSpacing: "normal",
    textAlign: "center",
    color: "#027aff",
    cursor: "pointer"
  },
  reject: {
    padding: "0 0 0 20px",
    width: "120px",
    height: "50px",
    margin: "5px 30px 5px 34px",
    padding: "15.8px 21.3px 10.3px 21.7px",
    borderRadius: "4px",
    border: "solid 1px #ef7200",
    backgroundColor: "#ffffff",
    display: "flex",
    justifyContent: "center",
    color: "#ef7200"
  },
  delete: {
    marginTop: "-42px",
    marginLeft: "56px",
    fontSize: ".5rem",
    [theme.breakpoints.up("md")]: {
      marginTop: "-42px",
      marginLeft: "56px",
      fontSize: ".3rem",
    },
    [theme.breakpoints.up("lg")]: {
      marginTop: "-42px",
      marginLeft: "56px",
      fontSize: ".5rem",
    },
  },
  expand: {
    transform: "rotate(0deg)",
    marginLeft: "auto",
    transition: theme.transitions.create("transform", {
      duration: theme.transitions.duration.shortest,
    }),
    "&:not(:first-child)": {
      marginLeft: "auto",
    },
  },
  expandOpen: {
    transform: "rotate(180deg)",
  },
  avatar: {
    backgroundColor: blue[500],
  },
  cardActions: {
    padding: "0px",
    paddingLeft: "15px",
    margin: "-8px 0 0 0",
    backgroundColor: " #f6f8ff",
  },
  deleteIcon: {
    width: "14px",
    height: "14px",
    color: "#ff2600",
    [theme.breakpoints.up("md")]: {
      width: "12px",
      height: "12px",
      color: "#ff2600",
    },
    [theme.breakpoints.up("lg")]: {
      width: "14px",
      height: "14px",
      color: "#ff2600",
    },
  },
  editIcon: {
    width: "14px",
    height: "14px",
    color: "#027aff",
    [theme.breakpoints.up("md")]: {
      width: "12px",
      height: "12px",
      color: "#027aff",
    },
    [theme.breakpoints.up("lg")]: {
      width: "14px",
      height: "14px",
      color: "#027aff",
    },
  },
  learningPath: {
    // backgroundColor: " #f6f8ff",
    fontSize: "14px",
    marginTop: "-2px",
    padding: " 1px 16px 6px",
    "&:last-child": {
      paddingBottom: "8px",
    },
  },
  pathTitle: {
    fontSize: "10px",
    color: "#888888",
    [theme.breakpoints.up("md")]: {
      fontSize: "9px",
      color: "#888888",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "10px",
      color: "#888888",
    },
  },
  listData: {
    // display: "flex",
    justifyContent: "space-between",
    fontSize: "10px",
  },
  deleteButton: {
    paddingRight: "4px",
    color: "red",
    fontWeight: "600",
    cursor: "pointer",
  },
  courseName: {
    color: "#282828",
    width: "80px",
    // padding: "0 0 0 50px",
    // height: "16px",
    // margin: "5px 30px 5px 34px",
    // padding: "15px 21px 11px 22px",
    borderRadius: "4px",
    // display: "flex",
    justifyContent: "center",
    //fontFamily: "ProximaNova",
    fontSize: "13px",
    fontweight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1.23",
    letterSpacing: "normal",
    textAlign: "center",
    // color: "#027aff"
  },
  courseStatus: {
    color: "#a5a5a5",
  },
  search: {
    fontWeight: 700,
  },
}));
